FROM docker.io/debian:latest

# Variables recommended for Debian Container image
# Recommended below
# github.com/phusion/baseimage-docker/issues/319#issuecomment-1066174043
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

# Update the OS
RUN apt-get update > /dev/null

# Install nodejs & npm
RUN apt-get install nodejs -y > /dev/null
RUN apt-get install npm -y > /dev/null

# Install Git 
RUN apt-get install git -y > /dev/null

# Install systemctl 
RUN apt-get install systemd -y > /dev/null

# Install sudo
RUN apt-get install sudo -y > /dev/null

# Install the prettier npm package globally
RUN npm install -g prettier > /dev/null

# Install PostgreSQL
RUN apt-get install postgresql postgresql-client -y > /dev/null

# Enable the systemd service for PostgreSQL
RUN systemctl enable postgresql

RUN sudo -u postgres psql 

# Create a PostgreSQL database for development
# devcontainer is the name of the user
RUN sudo -u postgres createuser devcontainer
# devcontainer is the name of the database
RUN sudo -u postgres createdb devcontainer
# devcontainer is the password
RUN sudo -u postgres psql -c "ALTER USER devcontainer PASSWORD 'devcontainer';"

# Name of the user within the container
ENV USER devcontainer

# Create a user account for python 3 development
# --home Specifies the user's home directory 
# --shell Specifies the shell that will assigned to the user on login 
# --disabled-password Don't assign a password when creating a user
# --gecos Skip the questionnaire.
RUN adduser \
--home "/home/${USER}" \
--shell "/bin/bash" \
--disabled-password \
--gecos "" \
"${USER}" > /dev/null

# Set a password for the user
RUN echo "${USER}:devcontainer" | chpasswd

# Add the user to the sudo group
RUN adduser "${USER}" sudo > /dev/null

# Switch to the new user 
USER "${USER}"
WORKDIR "/home/${USER}"

# Add the user's bin directory to the PATH
ENV PATH="${PATH}:/home/${USER}/.local/bin"
